In [1]:
import pandas as pd
import re
import swifter

In [2]:
test = pd.read_csv('/home/ubuntu/recsys_challenge_2020/competetion_submission_phase/data/like/test.ffm', sep = ' '\
                  ,header = None, usecols = [1,2,3,4,5,6,7,8,9,10,11])

In [3]:
test.head()

,1,2,3,4,5,6,7,8,9,10,11
0,1:1:1.0445731675303e-06,2:2:2.8108609869585045e-05,3:3:1.02096493548357e-06,4:4:0.0003559286214810339,5:5:1,6:8:1,7:9285322:1,8:15702463:1,9:15702468:1,10:42963993:1,11:42963996:1
1,1:1:1.6642352160652236e-06,2:2:5.936538404456362e-05,3:3:1.02096493548357e-06,4:4:0.0003559286214810339,5:6:1,6:8:1,7:3367747:1,8:15702463:1,9:15702468:1,10:42963993:1,11:42963996:1
2,1:1:3.816232987477223e-05,2:2:0.00014841346011140903,3:3:1.0577564646901852e-05,4:4:2.489381727620326e-05,5:6:1,6:11:1,7:598658:1,8:15702463:1,9:15702472:1,10:42963993:1,11:42963996:1
3,1:1:2.3989773593280617e-06,2:2:4.160074260698587e-05,3:3:7.183546077591606e-06,4:4:0.00023357815784692845,5:6:1,6:13:1,7:1678849:1,8:15702463:1,9:15702475:1,10:42963993:1,11:42963996:1
4,1:1:9.020508963672675e-06,2:2:0.00047155003917215873,3:3:1.3796823452480677e-07,4:4:6.461799378078293e-05,5:6:1,6:11:1,7:5602018:1,8:15702463:1,9:41198553:1,10:42963993:1,11:42963995:1

In [4]:
test_df = test.swifter.apply(lambda s: s.str.replace('^\d+:', ''))

HBox(children=(FloatProgress(value=0.0, description='Pandas Apply', max=11.0, style=ProgressStyle(description_â€¦

In [5]:
test_df.head()

,1,2,3,4,5,6,7,8,9,10,11
0,1:1.0445731675303e-06,2:2.8108609869585045e-05,3:1.02096493548357e-06,4:0.0003559286214810339,5:1,8:1,9285322:1,15702463:1,15702468:1,42963993:1,42963996:1
1,1:1.6642352160652236e-06,2:5.936538404456362e-05,3:1.02096493548357e-06,4:0.0003559286214810339,6:1,8:1,3367747:1,15702463:1,15702468:1,42963993:1,42963996:1
2,1:3.816232987477223e-05,2:0.00014841346011140903,3:1.0577564646901852e-05,4:2.489381727620326e-05,6:1,11:1,598658:1,15702463:1,15702472:1,42963993:1,42963996:1
3,1:2.3989773593280617e-06,2:4.160074260698587e-05,3:7.183546077591606e-06,4:0.00023357815784692845,6:1,13:1,1678849:1,15702463:1,15702475:1,42963993:1,42963996:1
4,1:9.020508963672675e-06,2:0.00047155003917215873,3:1.3796823452480677e-07,4:6.461799378078293e-05,6:1,11:1,5602018:1,15702463:1,41198553:1,42963993:1,42963995:1

In [6]:
test_df1 = test.swifter.applymap(lambda x: ':'.join(str(x).split(':')[1:]))

HBox(children=(FloatProgress(value=0.0, description='Pandas Apply', max=136783218.0, style=ProgressStyle(descrâ€¦

In [7]:
test_df1.head()

,1,2,3,4,5,6,7,8,9,10,11
0,1:1.0445731675303e-06,2:2.8108609869585045e-05,3:1.02096493548357e-06,4:0.0003559286214810339,5:1,8:1,9285322:1,15702463:1,15702468:1,42963993:1,42963996:1
1,1:1.6642352160652236e-06,2:5.936538404456362e-05,3:1.02096493548357e-06,4:0.0003559286214810339,6:1,8:1,3367747:1,15702463:1,15702468:1,42963993:1,42963996:1
2,1:3.816232987477223e-05,2:0.00014841346011140903,3:1.0577564646901852e-05,4:2.489381727620326e-05,6:1,11:1,598658:1,15702463:1,15702472:1,42963993:1,42963996:1
3,1:2.3989773593280617e-06,2:4.160074260698587e-05,3:7.183546077591606e-06,4:0.00023357815784692845,6:1,13:1,1678849:1,15702463:1,15702475:1,42963993:1,42963996:1
4,1:9.020508963672675e-06,2:0.00047155003917215873,3:1.3796823452480677e-07,4:6.461799378078293e-05,6:1,11:1,5602018:1,15702463:1,41198553:1,42963993:1,42963995:1

In [4]:
test.swifter.apply(lambda s: s.str.split('(^[a-z0-9]+\:(.*))').str[-2])

HBox(children=(FloatProgress(value=0.0, description='Pandas Apply', max=11.0, style=ProgressStyle(description_â€¦

,1,2,3,4,5,6,7,8,9,10,11
0,1:1.0445731675303e-06,2:2.8108609869585045e-05,3:1.02096493548357e-06,4:0.0003559286214810339,5:1,8:1,9285322:1,15702463:1,15702468:1,42963993:1,42963996:1
1,1:1.6642352160652236e-06,2:5.936538404456362e-05,3:1.02096493548357e-06,4:0.0003559286214810339,6:1,8:1,3367747:1,15702463:1,15702468:1,42963993:1,42963996:1
2,1:3.816232987477223e-05,2:0.00014841346011140903,3:1.0577564646901852e-05,4:2.489381727620326e-05,6:1,11:1,598658:1,15702463:1,15702472:1,42963993:1,42963996:1
3,1:2.3989773593280617e-06,2:4.160074260698587e-05,3:7.183546077591606e-06,4:0.00023357815784692845,6:1,13:1,1678849:1,15702463:1,15702475:1,42963993:1,42963996:1
4,1:9.020508963672675e-06,2:0.00047155003917215873,3:1.3796823452480677e-07,4:6.461799378078293e-05,6:1,11:1,5602018:1,15702463:1,41198553:1,42963993:1,42963995:1
...,...,...,...,...,...,...,...,...,...,...,...
12434833,1:4.770512542221006e-05,2:0.00018731577617091475,3:5.15081408892612e-07,4:0.0001408884126695759,6:1,10:1,1542193:1,15702463:1,42891073:1,42963993:1,42963995:1
12434834,1:0.00015709318161858223,2:0.0003298826454294501,3:1.6896509788138002e-05,4:6.77959279011493e-05,6:1,11:1,95876:1,15702463:1,27833865:1,42963993:1,42963995:1
12434835,1:3.881740118322343e-05,2:1.798951031653443e-05,3:7.358305841323028e-08,4:2.966071845675282e-05,6:1,13:1,125550:1,15702463:1,42784662:1,42963993:1,42963995:1
12434836,1:3.7489553936362884e-05,2:0.0009262349124225664,3:6.594881610285764e-06,4:0.00024523058295493853,5:1,8:1,1146104:1,15702463:1,27833875:1,42963993:1,42963996:1
12434837,1:3.853412710389319e-05,2:0.000816049161733793,3:6.594881610285764e-06,4:0.00024523058295493853,5:1,8:1,9345010:1,15702463:1,27833875:1,42963993:1,42963996:1